faye:
  server: http://localhost:9292/faye
  secret_token: 7650981269q2871928631823791287e
mappings:
  - source: faye:///stat
    target: rabbitmq://exchange/stat
  - source: faye:///register/listener
    target: rabbitmq://exchange/register.listener
  - source: rabbitmq://queue/log
    target: faye:///log
  - source: faye:///audit
    target: rabbitmq://exchange/audit