#!/bin/bash
# Wed Aug  7 17:11:42 CEST 2013
# Phil Hofmann
# Switzerland, Zurich, Colab

################################################################################
# standard vars stolen from cconf
#
__pwd="$(pwd -P)"
__mydir="${0%/*}"; __abs_mydir="$(cd "$__mydir" && pwd -P)"
__myname=${0##*/}; __abs_myname="$__abs_mydir/$__myname"

################################################################################
# Init rbenv
#

. ~/bin/rbenv_init

################################################################################
# Defaults
#
private_pub="bundle exec rackup private_pub.ru -E production"
private_pub_process="private_pub master"

# Rails is always located below ~/app/current
cd ~/app/current

case $1 in
    start)
        ${private_pub}
    ;;

    # foreground)
    #     ${private_pub} --listen "$(pwd -P)/unicorn.sock"
    # ;;
    # 
    # debug)
    #     ${private_pub} --debug --listen "$(pwd -P)/unicorn.sock"
    # ;;
    # 
    # debug-direct)
    #     ${private_pub} --debug --listen 0.0.0.0:3000
    # ;;

    stop)
        pkill -f "$private_pub_process"
    ;;

    # graceful-stop)
    #     pkill -QUIT -f "$private_pub_process"
    # ;;
    # 
    # reload)
    #     pkill -USR2 -f "$private_pub_process"
    # ;;
    # 
    # pid)
    #     pgrep -f "$private_pub_process"
    # ;;
    
    restart)
        "$0" stop
        "$0" start
    ;;

    *)
        cat << eof
$0:
    start:          start private_pub and daemonize
    foreground:     start private_pub and stay in foreground

    debug:          start private_pub with debug flag
    debug-direct:   start private_pub with debug flag and listen on 0.0.0.0:3000

    stop:           stop existing private_pub processes
    graceful-stop:  stop existing private_pub processes (gracefully)

    reload:         reload private_pub configuration
    restart:        stop and start

    pid:            show pid if running
eof

esac
