require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentsController do
  
  before do
    @user = FactoryGirl.create(:user)
    @status_update = FactoryGirl.create(:status_update, :user_id => @user.id)
    @commenter = FactoryGirl.create(:user)
    
  end

  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:comment).merge(:user_id => @commenter.id, :commentable_id => @status_update.id, :commentable_type => @status_update.class.to_s)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all comments as @comments" do
      comment = Comment.create! valid_attributes
      get :index, {:user_id => @user, :status_update_id => @status_update.id }, valid_session
      assigns(:comments).should eq([comment])
    end
  end

  describe "GET show" do
    it "assigns the requested comment as @comment" do
      comment = Comment.create! valid_attributes
      get :show, {:id => comment.to_param, :user_id => @user, :status_update_id => @status_update.id }, valid_session
      assigns(:comment).should eq(comment)
    end
  end

  describe "GET new" do
    it "assigns a new comment as @comment" do
      get :new, { :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
      assigns(:comment).should be_a_new(Comment)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment as @comment" do
      comment = Comment.create! valid_attributes
      get :edit, {:id => comment.to_param, :status_update_id => @status_update.id, :user_id => @user.id}, valid_session
      assigns(:comment).should eq(comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comment" do
        sign_in(@commenter) 
        puts "##############\n NEW: commenter: #{@commenter.id} - stauts_update: #{@status_update.inspect}\n###############"
        expect {
          post :create, {:comment => valid_attributes, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
        }.to change(Comment, :count).by(1)
      end

      it "assigns a newly created comment as @comment" do
        post :create, {:comment => valid_attributes, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
        assigns(:comment).should be_a(Comment)
        assigns(:comment).should be_persisted
      end

      it "redirects to the created comment - at given status_updates thread" do
        puts "##############\n commenter: #{@commenter.id} - stauts_update: #{@status_update.inspect} comment: #{Comment.last.inspect}\n###############"
        post :create, {:comment => valid_attributes, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
        response.should redirect_to(user_status_update_comments_path(:user_id => @user, :status_update_id => @status_update))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comment as @comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, {:comment => {},:user_id => @user.id, :status_update_id => @status_update.id }, valid_session
        assigns(:comment).should be_a_new(Comment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        post :create, {:comment => {}, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment" do
        
        comment = Comment.create! valid_attributes
        # Assuming there are no other comments in the database, this
        # specifies that the Comment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comment.to_param, :user_id => @user.id, :status_update_id => @status_update.id , :comment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested comment as @comment" do
        
        comment = Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :user_id => @user.id, :status_update_id => @status_update.id , :comment => valid_attributes}, valid_session
        assigns(:comment).should eq(comment)
      end

      it "redirects to the comment" do
        
        comment = Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :user_id => @user.id, :status_update_id => @status_update.id , :comment => valid_attributes}, valid_session
        response.should redirect_to(user_status_update_url(:user_id => @user.id, :status_update_id => @status_update.id ))
      end
    end

    describe "with invalid params" do
      it "assigns the comment as @comment" do
        
        comment = Comment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment.to_param,:user_id => @user.id, :status_update_id => @status_update.id , :comment => {}}, valid_session
        assigns(:comment).should eq(comment)
      end

      it "re-renders the 'edit' template" do
        
        comment = Comment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comment.any_instance.stub(:save).and_return(false)
        put :update, {:id => comment.to_param,:user_id => @user.id, :status_update_id => @status_update.id , :comment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment" do
      comment = Comment.create! valid_attributes
      expect {
        delete :destroy, {:id => comment.to_param, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
      }.to change(Comment, :count).by(-1)
    end

    it "redirects to the comments list" do
      comment = Comment.create! valid_attributes
      delete :destroy, {:id => comment.to_param, :user_id => @user.id, :status_update_id => @status_update.id}, valid_session
      response.should redirect_to(user_status_update_comments_path(:user_id => @user.id, :status_update_id => @status_update.id))
    end
  end

end
