require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreditAccountsController do
  
  before do
    @user = FactoryGirl.create(:user)  
  end


  # This should return the minimal set of attributes required to create a valid
  # CreditAccount. As you add validations to CreditAccount, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:credit_account, user_id: @user.id)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CreditAccountsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all credit_accounts as @credit_accounts" do
      credit_account = CreditAccount.create! valid_attributes
      get :index, {}, valid_session
      assigns(:credit_accounts).should eq([credit_account])
    end
  end

  describe "GET show" do
    it "assigns the requested credit_account as @credit_account" do
      credit_account = CreditAccount.create! valid_attributes
      get :show, {:id => credit_account.to_param}, valid_session
      assigns(:credit_account).should eq(credit_account)
    end
  end

  describe "GET new" do
    it "assigns a new credit_account as @credit_account" do
      get :new, {}, valid_session
      assigns(:credit_account).should be_a_new(CreditAccount)
    end
  end

  describe "GET edit" do
    it "assigns the requested credit_account as @credit_account" do
      credit_account = CreditAccount.create! valid_attributes
      get :edit, {:id => credit_account.to_param}, valid_session
      assigns(:credit_account).should eq(credit_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CreditAccount" do
        expect {
          post :create, {:credit_account => valid_attributes}, valid_session
        }.to change(CreditAccount, :count).by(1)
      end

      it "assigns a newly created credit_account as @credit_account" do
        post :create, {:credit_account => valid_attributes}, valid_session
        assigns(:credit_account).should be_a(CreditAccount)
        assigns(:credit_account).should be_persisted
      end

      it "redirects to the created credit_account" do
        post :create, {:credit_account => valid_attributes}, valid_session
        response.should redirect_to(CreditAccount.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved credit_account as @credit_account" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreditAccount.any_instance.stub(:save).and_return(false)
        post :create, {:credit_account => {}}, valid_session
        assigns(:credit_account).should be_a_new(CreditAccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreditAccount.any_instance.stub(:save).and_return(false)
        post :create, {:credit_account => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested credit_account" do
        credit_account = CreditAccount.create! valid_attributes
        # Assuming there are no other credit_accounts in the database, this
        # specifies that the CreditAccount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CreditAccount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => credit_account.to_param, :credit_account => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested credit_account as @credit_account" do
        credit_account = CreditAccount.create! valid_attributes
        put :update, {:id => credit_account.to_param, :credit_account => valid_attributes}, valid_session
        assigns(:credit_account).should eq(credit_account)
      end

      it "redirects to the credit_account" do
        credit_account = CreditAccount.create! valid_attributes
        put :update, {:id => credit_account.to_param, :credit_account => valid_attributes}, valid_session
        response.should redirect_to(credit_account)
      end
    end

    describe "with invalid params" do
      it "assigns the credit_account as @credit_account" do
        credit_account = CreditAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreditAccount.any_instance.stub(:save).and_return(false)
        put :update, {:id => credit_account.to_param, :credit_account => {}}, valid_session
        assigns(:credit_account).should eq(credit_account)
      end

      it "re-renders the 'edit' template" do
        credit_account = CreditAccount.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreditAccount.any_instance.stub(:save).and_return(false)
        put :update, {:id => credit_account.to_param, :credit_account => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested credit_account" do
      credit_account = CreditAccount.create! valid_attributes
      expect {
        delete :destroy, {:id => credit_account.to_param}, valid_session
      }.to change(CreditAccount, :count).by(-1)
    end

    it "redirects to the credit_accounts list" do
      credit_account = CreditAccount.create! valid_attributes
      delete :destroy, {:id => credit_account.to_param}, valid_session
      response.should redirect_to(credit_accounts_url)
    end
  end

end
