require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaypalPaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # PaypalPayment. As you add validations to PaypalPayment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaypalPaymentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paypal_payments as @paypal_payments" do
      paypal_payment = PaypalPayment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paypal_payments).should eq([paypal_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested paypal_payment as @paypal_payment" do
      paypal_payment = PaypalPayment.create! valid_attributes
      get :show, {:id => paypal_payment.to_param}, valid_session
      assigns(:paypal_payment).should eq(paypal_payment)
    end
  end

  describe "GET new" do
    it "assigns a new paypal_payment as @paypal_payment" do
      get :new, {}, valid_session
      assigns(:paypal_payment).should be_a_new(PaypalPayment)
    end
  end

  describe "GET edit" do
    it "assigns the requested paypal_payment as @paypal_payment" do
      paypal_payment = PaypalPayment.create! valid_attributes
      get :edit, {:id => paypal_payment.to_param}, valid_session
      assigns(:paypal_payment).should eq(paypal_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaypalPayment" do
        expect {
          post :create, {:paypal_payment => valid_attributes}, valid_session
        }.to change(PaypalPayment, :count).by(1)
      end

      it "assigns a newly created paypal_payment as @paypal_payment" do
        post :create, {:paypal_payment => valid_attributes}, valid_session
        assigns(:paypal_payment).should be_a(PaypalPayment)
        assigns(:paypal_payment).should be_persisted
      end

      it "redirects to the created paypal_payment" do
        post :create, {:paypal_payment => valid_attributes}, valid_session
        response.should redirect_to(PaypalPayment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paypal_payment as @paypal_payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaypalPayment.any_instance.stub(:save).and_return(false)
        post :create, {:paypal_payment => {}}, valid_session
        assigns(:paypal_payment).should be_a_new(PaypalPayment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaypalPayment.any_instance.stub(:save).and_return(false)
        post :create, {:paypal_payment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paypal_payment" do
        paypal_payment = PaypalPayment.create! valid_attributes
        # Assuming there are no other paypal_payments in the database, this
        # specifies that the PaypalPayment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaypalPayment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => paypal_payment.to_param, :paypal_payment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested paypal_payment as @paypal_payment" do
        paypal_payment = PaypalPayment.create! valid_attributes
        put :update, {:id => paypal_payment.to_param, :paypal_payment => valid_attributes}, valid_session
        assigns(:paypal_payment).should eq(paypal_payment)
      end

      it "redirects to the paypal_payment" do
        paypal_payment = PaypalPayment.create! valid_attributes
        put :update, {:id => paypal_payment.to_param, :paypal_payment => valid_attributes}, valid_session
        response.should redirect_to(paypal_payment)
      end
    end

    describe "with invalid params" do
      it "assigns the paypal_payment as @paypal_payment" do
        paypal_payment = PaypalPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaypalPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => paypal_payment.to_param, :paypal_payment => {}}, valid_session
        assigns(:paypal_payment).should eq(paypal_payment)
      end

      it "re-renders the 'edit' template" do
        paypal_payment = PaypalPayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaypalPayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => paypal_payment.to_param, :paypal_payment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paypal_payment" do
      paypal_payment = PaypalPayment.create! valid_attributes
      expect {
        delete :destroy, {:id => paypal_payment.to_param}, valid_session
      }.to change(PaypalPayment, :count).by(-1)
    end

    it "redirects to the paypal_payments list" do
      paypal_payment = PaypalPayment.create! valid_attributes
      delete :destroy, {:id => paypal_payment.to_param}, valid_session
      response.should redirect_to(paypal_payments_url)
    end
  end

end
