require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProfileSettingsController do


  before  do
    @user = FactoryGirl.create(:user)
  end
  
  # This should return the minimal set of attributes required to create a valid
  # ProfileSetting. As you add validations to ProfileSetting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:profile_setting).merge(:user_id => @user.id)
  end
  

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProfileSettingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET show" do
    it "assigns the requested profile_setting as @profile_setting" do
      profile_setting = @user.profile_setting
      get :show, {:id => profile_setting.to_param, :user_id => @user.id}, valid_session
      assigns(:profile_setting).should eq(profile_setting)
    end
  end

  #describe "GET new" do
  #  it "assigns a new profile_setting as @profile_setting" do
  #    get :new, {:user_id => @user}, valid_session
  #    assigns(:profile_setting).should be_a_new(ProfileSetting)
  #  end
  #end

  describe "GET edit" do
    it "assigns the requested profile_setting as @profile_setting" do
      profile_setting = @user.profile_setting #ProfileSetting.create! valid_attributes
      get :edit, {:user_id => @user}, valid_session
      assigns(:profile_setting).should eq(profile_setting)
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested profile_setting" do
        profile_setting = ProfileSetting.create! valid_attributes
        # Assuming there are no other profile_settings in the database, this
        # specifies that the ProfileSetting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProfileSetting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, { :user_id => profile_setting.user, :profile_setting => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested profile_setting as @profile_setting" do
        profile_setting = @user.profile_setting
        put :update, {:user_id => profile_setting.user.id, :profile_setting => valid_attributes }, valid_session
        assigns(:profile_setting).should eq(profile_setting)
      end

      it "redirects to the profile_setting" do
        profile_setting = ProfileSetting.create! valid_attributes
        put :update, {:user_id => profile_setting.user, :profile_setting => valid_attributes}, valid_session
        response.should redirect_to(user_profile_setting_url(:user_id => profile_setting.user))
      end
    end

    describe "with invalid params" do
      it "assigns the profile_setting as @profile_setting" do
        profile_setting = ProfileSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfileSetting.any_instance.stub(:save).and_return(false)
        put :update, {:user_id => @user, :profile_setting => {}}, valid_session
        assigns(:profile_setting).should eq(@user.profile_setting)
      end

      it "re-renders the 'edit' template" do
        profile_setting = ProfileSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfileSetting.any_instance.stub(:save).and_return(false)
        put :update, {:user_id => @user, :profile_setting => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end
  
  describe "DELETE portrait" do
    it "redirects to users profile_setting" do 
    #it "destroys the attached portrait" do
      profile_setting = FactoryGirl.create(:profile_setting_with_portrait, :user => @user)
      profile_setting.portrait.exists?.should be_true
      delete :destroy_portrait, { :user_id => @user }, valid_session
      # FIXME: this test is not working properly
      #profile_setting.portrait.exists?.should be_false
      response.should redirect_to(user_profile_setting_path(:user_id => @user))
    end
  end

end
