require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatusUpdatesController do

  before  do
    @user = FactoryGirl.create(:user)
    request.env['warden'].stub :authenticate! => @user
    controller.stub :current_user => @user
  end
  
  # This should return the minimal set of attributes required to create a valid
  # StatusUpdate. As you add validations to StatusUpdate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    FactoryGirl.attributes_for(:status_update).merge(:user_id => @user.id)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatusUpdatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end


  describe "GET show" do
    it "assigns the requested status_update as @status_update" do
      status_update = StatusUpdate.create! valid_attributes
      get :show, {:id => status_update.to_param, :user_id => @user}, valid_session
      assigns(:status_update).should eq(status_update)
    end
  end

  describe "GET new" do
    it "assigns a new status_update as @status_update" do
      get :new, {:user_id => @user.id}, valid_session
      assigns(:status_update).should be_a_new(StatusUpdate)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_update as @status_update" do
      status_update = StatusUpdate.create! valid_attributes
      get :edit, {:id => status_update.to_param, :user_id => @user}, valid_session
      assigns(:status_update).should eq(status_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StatusUpdate" do
        expect {
          post :create, { :status_update => valid_attributes, :user_id => @user.id }, valid_session 
        }.to change(StatusUpdate, :count).by(1)
      end

      it "assigns a newly created status_update as @status_update" do
        post :create, {:status_update => valid_attributes, :user_id => @user.id}, valid_session
        assigns(:status_update).should be_a(StatusUpdate)
        assigns(:status_update).should be_persisted
      end

      it "redirects to the created status_update" do
        post :create, {:status_update => valid_attributes, :user_id => @user.id}, valid_session
        response.should redirect_to user_path(:id => @user)# (StatusUpdate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_update as @status_update" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:status_update => {}, :user_id => @user}, valid_session
        assigns(:status_update).should be_a_new(StatusUpdate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:status_update => {}, :user_id => @user}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_update" do
        status_update = StatusUpdate.create! valid_attributes
        # Assuming there are no other status_updates in the database, this
        # specifies that the StatusUpdate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StatusUpdate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => status_update.to_param, :status_update => {'these' => 'params'}, :user_id => @user}, valid_session
      end
  
      it "assigns the requested status_update as @status_update" do
        status_update = StatusUpdate.create! valid_attributes
        put :update, {:id => status_update.to_param, :status_update => valid_attributes, :user_id => @user}, valid_session
        assigns(:status_update).should eq(status_update)
      end#
  
      it "redirects to the status_update" do
        status_update = StatusUpdate.create! valid_attributes
        put :update, {:id => status_update.to_param, :status_update => valid_attributes, :user_id => @user}, valid_session
        response.should redirect_to( user_status_update_path(:user_id => @user, :id => status_update.id))
      end
    end

    describe "with invalid params" do
      it "assigns the status_update as @status_update" do
        status_update = StatusUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_update.to_param, :status_update => {}, :user_id => @user}, valid_session
        assigns(:status_update).should eq(status_update)
      end

      it "re-renders the 'edit' template" do
        status_update = StatusUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_update.to_param, :status_update => {}, :user_id => @user}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_update" do
      status_update = StatusUpdate.create!( valid_attributes)
      expect {
        delete :destroy, {:id => status_update.to_param, :user_id => @user}, valid_session
      }.to change(StatusUpdate, :count).by(-1)
    end

    it "redirects to the status_updates list" do
      status_update = StatusUpdate.create! valid_attributes
      delete :destroy, {:id => status_update.to_param, :user_id => @user}, valid_session
      response.should redirect_to( user_status_updates_url(:user_id => @user))
    end
  end


end
