require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VideoSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # VideoSession. As you add validations to VideoSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VideoSessionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all video_sessions as @video_sessions" do
      video_session = VideoSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:video_sessions).should eq([video_session])
    end
  end

  describe "GET show" do
    it "assigns the requested video_session as @video_session" do
      video_session = VideoSession.create! valid_attributes
      get :show, {:id => video_session.to_param}, valid_session
      assigns(:video_session).should eq(video_session)
    end
  end

  describe "GET new" do
    it "assigns a new video_session as @video_session" do
      get :new, {}, valid_session
      assigns(:video_session).should be_a_new(VideoSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested video_session as @video_session" do
      video_session = VideoSession.create! valid_attributes
      get :edit, {:id => video_session.to_param}, valid_session
      assigns(:video_session).should eq(video_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VideoSession" do
        expect {
          post :create, {:video_session => valid_attributes}, valid_session
        }.to change(VideoSession, :count).by(1)
      end

      it "assigns a newly created video_session as @video_session" do
        post :create, {:video_session => valid_attributes}, valid_session
        assigns(:video_session).should be_a(VideoSession)
        assigns(:video_session).should be_persisted
      end

      it "redirects to the created video_session" do
        post :create, {:video_session => valid_attributes}, valid_session
        response.should redirect_to(VideoSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved video_session as @video_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        VideoSession.any_instance.stub(:save).and_return(false)
        post :create, {:video_session => {}}, valid_session
        assigns(:video_session).should be_a_new(VideoSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VideoSession.any_instance.stub(:save).and_return(false)
        post :create, {:video_session => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested video_session" do
        video_session = VideoSession.create! valid_attributes
        # Assuming there are no other video_sessions in the database, this
        # specifies that the VideoSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VideoSession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => video_session.to_param, :video_session => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested video_session as @video_session" do
        video_session = VideoSession.create! valid_attributes
        put :update, {:id => video_session.to_param, :video_session => valid_attributes}, valid_session
        assigns(:video_session).should eq(video_session)
      end

      it "redirects to the video_session" do
        video_session = VideoSession.create! valid_attributes
        put :update, {:id => video_session.to_param, :video_session => valid_attributes}, valid_session
        response.should redirect_to(video_session)
      end
    end

    describe "with invalid params" do
      it "assigns the video_session as @video_session" do
        video_session = VideoSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VideoSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => video_session.to_param, :video_session => {}}, valid_session
        assigns(:video_session).should eq(video_session)
      end

      it "re-renders the 'edit' template" do
        video_session = VideoSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VideoSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => video_session.to_param, :video_session => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested video_session" do
      video_session = VideoSession.create! valid_attributes
      expect {
        delete :destroy, {:id => video_session.to_param}, valid_session
      }.to change(VideoSession, :count).by(-1)
    end

    it "redirects to the video_sessions list" do
      video_session = VideoSession.create! valid_attributes
      delete :destroy, {:id => video_session.to_param}, valid_session
      response.should redirect_to(video_sessions_url)
    end
  end

end
